<a href="https://colab.research.google.com/github/Alwinaj/Learn-py/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [1]:
#please type your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-09-30',periods=4)
ok = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("Head:\n", ok.head())
print("\nTail:\n", ok.tail())
print("\nIndex:\n", ok.index)
print("\nColumns:\n", ok.columns)
print("\nValues:\n", ok.values)
print("\nStatistics:\n", ok.describe(include='all'))

Head:
                    A         B         C         D
2021-09-30  0.964130  0.815896 -0.282415 -2.271751
2021-10-01 -0.628853  1.478582  1.049612 -0.132305
2021-10-02 -0.955779  0.164077 -0.710333  0.167878
2021-10-03 -0.067736 -1.036016 -1.233336 -0.606778

Tail:
                    A         B         C         D
2021-09-30  0.964130  0.815896 -0.282415 -2.271751
2021-10-01 -0.628853  1.478582  1.049612 -0.132305
2021-10-02 -0.955779  0.164077 -0.710333  0.167878
2021-10-03 -0.067736 -1.036016 -1.233336 -0.606778

Index:
 DatetimeIndex(['2021-09-30', '2021-10-01', '2021-10-02', '2021-10-03'], dtype='datetime64[ns]', freq='D')

Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')

Values:
 [[ 0.96412971  0.81589597 -0.28241501 -2.27175103]
 [-0.62885276  1.47858158  1.04961208 -0.13230468]
 [-0.95577932  0.16407659 -0.71033267  0.16787764]
 [-0.06773557 -1.03601636 -1.23333627 -0.60677824]]

Statistics:
               A         B         C         D
count  4.000000  4.000000  4.0

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [2]:
#please provide your answer below this line.
import numpy as np
import pandas as pd
datetie = pd.date_range('2021-09-30',periods=4)
ok = pd.DataFrame(np.random.randn(4,4), index=datetie, columns=list('ABCD'))
print("Head:\n", ok.head())
print("\nTail:\n", ok.tail())
print("\nIndex:\n", ok.index)
print("\nColumns:\n", ok.columns)
print("\nValues:\n", ok.values)
print("\nStatistics:\n", ok.describe(include='all'))

Head:
                    A         B         C         D
2021-09-30 -0.742001  0.238664 -2.151923 -0.169715
2021-10-01  0.357348  0.219903  0.611873  1.086998
2021-10-02  0.606857  0.252512  0.483200 -0.425283
2021-10-03  0.892701  0.841490  2.415678  0.663037

Tail:
                    A         B         C         D
2021-09-30 -0.742001  0.238664 -2.151923 -0.169715
2021-10-01  0.357348  0.219903  0.611873  1.086998
2021-10-02  0.606857  0.252512  0.483200 -0.425283
2021-10-03  0.892701  0.841490  2.415678  0.663037

Index:
 DatetimeIndex(['2021-09-30', '2021-10-01', '2021-10-02', '2021-10-03'], dtype='datetime64[ns]', freq='D')

Columns:
 Index(['A', 'B', 'C', 'D'], dtype='object')

Values:
 [[-0.74200083  0.23866383 -2.15192278 -0.16971451]
 [ 0.35734771  0.21990287  0.61187265  1.08699787]
 [ 0.60685674  0.25251229  0.48320007 -0.42528345]
 [ 0.89270146  0.84148984  2.41567784  0.66303675]]

Statistics:
               A         B         C         D
count  4.000000  4.000000  4.0