<a href="https://colab.research.google.com/github/Alwinaj/Learn-py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [14]:
#please provide your answer below this line.
import numpy as np
  
matrix = np.random.randint(10, size=(3, 3))
print(matrix)

[[6 6 8]
 [6 9 0]
 [4 9 3]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [15]:
#please provide your answer below this line.
import numpy as np
 
matrix = np.random.randint(10,size=(4,4))
print(matrix)
 
newm = matrix.reshape(2,8)
print("The Reshaped Matrix is \n",newm)
vstack = np.vstack(newm,)
print("Vertically Stacked Matrix is \n",vstack)
hstack = np.hstack(newm)
print("Horizontally Stacked Matrix is \n",hstack)

[[3 6 9 9]
 [5 3 7 0]
 [7 0 2 0]
 [6 4 8 2]]
The Reshaped Matrix is 
 [[3 6 9 9 5 3 7 0]
 [7 0 2 0 6 4 8 2]]
Vertically Stacked Matrix is 
 [[3 6 9 9 5 3 7 0]
 [7 0 2 0 6 4 8 2]]
Horizontally Stacked Matrix is 
 [3 6 9 9 5 3 7 0 7 0 2 0 6 4 8 2]
