<a href="https://colab.research.google.com/github/Alwinaj/Learn-py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.
import numpy as np
matrix1 = np.random.randint(0,10,(3,3))
matrix2 = np.random.randint(0,10,(3,3))
 
print(matrix1)
print(matrix2)
 
dot = np.dot(matrix1,matrix2)
print(dot)

[[6 9 9]
 [0 1 4]
 [8 7 3]]
[[5 0 8]
 [4 5 4]
 [1 0 9]]
[[ 75  45 165]
 [  8   5  40]
 [ 71  35 119]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [4]:
#please provide your answer below this line.
import numpy as np
matrix = [[55,25,15],[30,44,2],[11,45,77]]
print(matrix)
det = np.linalg.det(matrix)
print(det)

[[55, 25, 15], [30, 44, 2], [11, 45, 77]]
137180.0000000001
